### ISSUE TITLE
オブジェクトの接頭辞削除ですべてのオブジェクトを削除してしまうミスを防ぐ方法を検討する

### ISSUE THREAD

**Issue by shinnya** [frugalos/frugalos#14]
すべてのデータを削除したいユースケースは実運用ではほぼないと想定されるため、プログラムのバグによりすべてのデータが消失してしまうのは避けられるといいかもしれないという話です。

# 以下 sile 先生のアイディア

個人的には、（例えば）以下のような許可リストファイルを起動時にfrugalosに指定するようにするのが良いのではないかと思っています:

```yaml
# なぜかYAML形式（RustならTOMLの方が良さそう)
allow_prefix_delete:
  - bucket: "foo"                                # 接頭辞削除を許可しているバケツ
    object_prefix: "xxxxx.timeshift."  # この文字列を接頭辞に含まない場合には、削除要求は拒否される
```
